### ISSUE TITLE
Does not working

### ISSUE THREAD

**Issue by nokia001** [timjong93/MMM-MPD#2]
Hallo,

here is my log:
> 0|mm       | Loading module helpers ...
0|mm       | No helper found for module: alert.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | No helper found for module: clock.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: calendar
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: email
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: MMM-MPD
0|mm       | No helper found for module: compliments.
0|mm       | No helper found for module: currentweather.
0|mm       | No helper found for module: MMM-forecast-io.
0|mm       | No helper found for module: weatherforecast.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: newsfeed
0|mm       | All module helpers loaded.
0|mm       | Starting server on port 8080 ... 
0|mm       | Server started ...
0|mm       | Connecting socket for: updatenotification
0|mm       | Connecting socket for: calendar
0|mm       | Starting node helper for: calendar
0|mm       | Connecting socket for: email
0|mm       | email helper started ...
0|mm       | Connecting socket for: MMM-MPD
0|mm       | Starting module helper: MMM-MPD
0|mm       | Connecting socket for: newsfeed
0|mm       | Starting module: newsfeed
0|mm       | Sockets connected & modules started ...
0|mm       | Launching application.

here my config:
`               {
                module:  "MMM-MPD",
                position: "middle_right",        // This can be any of the regions.
                config: {
                        hostname: 'localhost',
                        port: '6600'
                        }

                },
`

I change the line in mpd_clients.js to:
`Module.register("MMM-MPD",{
` 

npm install:

> npm WARN mmm_mpd_client@0.1.0 No repository field.
npm WARN mmm_mpd_client@0.1.0 license should be a valid SPDX license expression

But no connection to mpd-demon and nothing shows on the screen.

Can you help?

**Comment by timjong93** [comment]
Sorry for the late reply, i'm going to make file names more consistent ;) this is al very confusing.
I haven't been able to recreate your issue. My guess at this moment, put the port number in as an integer instead of a string.

You should also be able to leave hostname and port out as these are the default values.
