### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by Waldehead** [timjong93/MMM-MPD#8]
Hello, I hope anybody can help me.

I installed it as described in the readme and the other issues.

When I start MM, following error appears:

``` 
    WARNING! Could not validate config file. Starting with default configuration. 
    Please correct syntax errors at or above this line: 
    ReferenceError: NodeHelper is not defined        
                                                                                                                                                                    
    at Object.<anonymous> (/home/pi/MagicMirror/modules/mpd_client/node_helper.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadModule (/home/pi/MagicMirror/js/app.js:124:17)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:158:5)
    at /home/pi/MagicMirror/js/app.js:160:6
```

MPD-Server is running on the same machine, my config is

```
                { 
                        module: "mpd_client",
                        position: "top_right",  // This can be any of the regions.
                        config: {
                                // See 'Configuration options' for more information.
                                hostname: "localhost",
                                port: 6600
                        }
                },
```

**Comment by coderpussy** [comment]
Take a look at:
https://github.com/coderpussy/MMM-MPD/tree/develop

The module is polished a little by me including also a fix for this issue.

I'm still waiting for merging my pull request.
I don't want to create new module on 3rd party page from Magic Mirror.

**Comment by Waldehead** [comment]
Thanks, your module works for me. But i needed to remove timjongs and clone yours via 
`git clone https://github.com/coderpussy/MMM-MPD/ -b develop ./MMM-MPD/`
switched then in the MMM-MPD folder, installed it via `npm install` and edited the config like in your readme. 
(Maybe test my command and update your readme, because the `git pull && npm install` does not work)

Thank you very much :)

Edit:
Just saw that you opened your own repository, this works fine, so thank you :)
(for anyone who stumbles upon my issue: https://github.com/coderpussy/MMM-Mopidy-MPD)
